/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 virtualGarden.gltf 
Author: Nicholas-3D (https://sketchfab.com/Nicholas01)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/greenhouse-park-fbx-free-b4fde1d1b8bc4cdd9002ddad4dbfb9c9
Title: Greenhouse Park FBX Free
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/virtualGarden.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -10, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={40}>
          <mesh geometry={nodes.GreenHouseStructure_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.GreenHouseStructure_Glass_Rough_0.geometry} material={materials.Glass_Rough} />
        </group>
        <mesh geometry={nodes.Floor_WetConcrete_0.geometry} material={materials.WetConcrete} position={[0, 2, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={40} />
        <mesh geometry={nodes.Ground_Grass_0.geometry} material={materials.Grass} position={[0, -10, -1600]} rotation={[-Math.PI / 2, 0, 0]} scale={70} />
        <mesh geometry={nodes.Pots_Small_Plants_0.geometry} material={materials.Plants} position={[-533.493, 0.106, -656.567]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small001_Plants_0.geometry} material={materials.Plants} position={[-465.68, 0.106, -656.709]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small002_Plants_0.geometry} material={materials.Plants} position={[-529.612, 0.106, -554.01]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small003_Plants_0.geometry} material={materials.Plants} position={[-462.184, 0.106, -553.636]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small004_Plants_0.geometry} material={materials.Plants} position={[-529.612, 0.115, -395.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small005_Plants_0.geometry} material={materials.Plants} position={[-462.184, 0.115, -395.145]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small006_Plants_0.geometry} material={materials.Plants} position={[-533.493, 0.115, -293.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small007_Plants_0.geometry} material={materials.Plants} position={[-465.68, 0.115, -293.364]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small008_Plants_0.geometry} material={materials.Plants} position={[-566.47, 0.115, -172.179]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small009_Plants_0.geometry} material={materials.Plants} position={[-462.184, 0.115, -171.805]} rotation={[-Math.PI / 2, 0, -1.833]} scale={100} />
        <mesh geometry={nodes.Pots_Small010_Plants_0.geometry} material={materials.Plants} position={[-529.612, 0.115, -65.193]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small011_Plants_0.geometry} material={materials.Plants} position={[-462.184, 0.115, -64.819]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small012_Plants_0.geometry} material={materials.Plants} position={[-683.493, 0.115, -293.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small013_Plants_0.geometry} material={materials.Plants} position={[-615.68, 0.115, -293.364]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small014_Plants_0.geometry} material={materials.Plants} position={[-745.767, 0.115, -172.179]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small015_Plants_0.geometry} material={materials.Plants} position={[-649.042, 0.115, -171.805]} rotation={[-Math.PI / 2, 0, -1.833]} scale={100} />
        <mesh geometry={nodes.Pots_Small016_Plants_0.geometry} material={materials.Plants} position={[-679.612, 0.115, -65.193]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small017_Plants_0.geometry} material={materials.Plants} position={[-612.184, 0.115, -64.819]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small018_Plants_0.geometry} material={materials.Plants} position={[-693.493, 0.106, -656.567]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small019_Plants_0.geometry} material={materials.Plants} position={[-625.68, 0.106, -656.709]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small020_Plants_0.geometry} material={materials.Plants} position={[-689.612, 0.106, -554.01]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small021_Plants_0.geometry} material={materials.Plants} position={[-622.184, 0.106, -553.636]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small022_Plants_0.geometry} material={materials.Plants} position={[-689.612, 0.115, -395.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small023_Plants_0.geometry} material={materials.Plants} position={[-622.184, 0.115, -395.145]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small044_Plants_0.geometry} material={materials.Plants} position={[-402.991, 111.617, -886.585]} rotation={[-Math.PI / 2, 0, 1.057]} scale={100} />
        <mesh geometry={nodes.Pots_Small053_Plants_0.geometry} material={materials.Plants} position={[-395.359, 111.617, -1198.422]} rotation={[-Math.PI / 2, 0, 1.92]} scale={100} />
        <mesh geometry={nodes.Pots_Small070_Plants_0.geometry} material={materials.Plants} position={[-412.921, 110.046, -1391.76]} rotation={[-Math.PI / 2, 0, -1.833]} scale={100} />
        <mesh geometry={nodes.Pots_Small077_Plants_0.geometry} material={materials.Plants} position={[-395.359, 111.617, -1960.907]} rotation={[-Math.PI / 2, 0, 1.92]} scale={100} />
        <mesh geometry={nodes.Pots_Small085_Plants_0.geometry} material={materials.Plants} position={[-465.68, 0.106, -1542.287]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Small114_Plants_0.geometry} material={materials.Plants} position={[-395.359, 111.617, -2746.689]} rotation={[-Math.PI / 2, 0, 1.92]} scale={100} />
        <mesh geometry={nodes.Pots_Small131_Plants_0.geometry} material={materials.Plants} position={[-414.199, 111.617, -2932.557]} rotation={[-Math.PI / 2, 0, -0.165]} scale={100} />
        <mesh geometry={nodes.Pots_Small024_Plants_0.geometry} material={materials.Plants} position={[380.458, 1.998, -1066.351]} rotation={[-Math.PI / 2, 0, -2.793]} scale={100} />
        <mesh geometry={nodes.Pots_Small025_Plants_0.geometry} material={materials.Plants} position={[298.149, 1.998, -190.35]} rotation={[-Math.PI / 2, 0, Math.PI / 9]} scale={100} />
        <mesh geometry={nodes.Pots_Small026_Plants_0.geometry} material={materials.Plants} position={[-190.896, 1.998, -1066.351]} rotation={[-Math.PI / 2, 0, -2.793]} scale={100} />
        <mesh geometry={nodes.Pots_Small027_Plants_0.geometry} material={materials.Plants} position={[303.846, 1.998, -2206.443]} rotation={[-Math.PI / 2, 0, -2.793]} scale={100} />
        <mesh geometry={nodes.Pots_Small028_Plants_0.geometry} material={materials.Plants} position={[303.846, 1.998, -2734.224]} rotation={[-Math.PI / 2, 0, -2.793]} scale={100} />
        <mesh geometry={nodes.Pots_Large001_Plants_0.geometry} material={materials.Plants} position={[-320.111, 14.014, -161.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large004_Plants_0.geometry} material={materials.Plants} position={[-320.111, 14.014, -281.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large002_Plants_0.geometry} material={materials.Plants} position={[-320.111, 14.014, -391.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large003_Plants_0.geometry} material={materials.Plants} position={[-140.111, 14.014, -281.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large_Plants_0.geometry} material={materials.Plants} position={[-320.111, 14.014, -61.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large005_Plants_0.geometry} material={materials.Plants} position={[-140.111, 14.014, -391.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large009_Plants_0.geometry} material={materials.Plants} position={[651.994, 125.64, -1401.334]} rotation={[-Math.PI / 2, 0, 2.707]} scale={100} />
        <mesh geometry={nodes.Pots_Large010_Plants_0.geometry} material={materials.Plants} position={[680.448, 125.64, -228.498]} rotation={[-Math.PI / 2, 0, -0.266]} scale={100} />
        <mesh geometry={nodes.Pots_Large012_Plants_0.geometry} material={materials.Plants} position={[674.502, 125.64, -401.422]} rotation={[-Math.PI / 2, 0, -0.479]} scale={100} />
        <mesh geometry={nodes.Pots_Large013_Plants_0.geometry} material={materials.Plants} position={[666.846, 125.64, -583.113]} rotation={[-Math.PI / 2, 0, 2.007]} scale={100} />
        <mesh geometry={nodes.Pots_Large014_Plants_0.geometry} material={materials.Plants} position={[671.788, 16.021, -775.165]} rotation={[-Math.PI / 2, 0, 0.097]} scale={100} />
        <mesh geometry={nodes.Pots_Large025_Plants_0.geometry} material={materials.Plants} position={[715.708, 125.64, -1604.376]} rotation={[-Math.PI / 2, 0, -0.616]} scale={100} />
        <mesh geometry={nodes.Pots_Large028_Plants_0.geometry} material={materials.Plants} position={[718.603, 125.64, -1786.875]} rotation={[-Math.PI / 2, 0, -0.903]} scale={100} />
        <mesh geometry={nodes.Pots_Large031_Plants_0.geometry} material={materials.Plants} position={[716.24, 125.64, -2127.892]} rotation={[-Math.PI / 2, 0, -1.601]} scale={100} />
        <mesh geometry={nodes.Pots_Large033_Plants_0.geometry} material={materials.Plants} position={[679.731, 125.64, -2898.38]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Pots_Large034_Plants_0.geometry} material={materials.Plants} position={[679.184, 125.64, -3057.534]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        <mesh geometry={nodes.Pots_Large036_Plants_0.geometry} material={materials.Plants} position={[676.821, 125.64, -2473.945]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        <mesh geometry={nodes.Pots_Large038_Plants_0.geometry} material={materials.Plants} position={[679.971, 125.64, -2311.706]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pots_Large040_Plants_0.geometry} material={materials.Plants} position={[672.696, 16.021, -1935.003]} rotation={[-Math.PI / 2, 0, 0.292]} scale={100} />
        <mesh geometry={nodes.Pots_Large044_Plants_0.geometry} material={materials.Plants} position={[672.696, 16.021, -2618.055]} rotation={[-Math.PI / 2, 0, 2.212]} scale={100} />
        <mesh geometry={nodes.Pots_Large046_Plants_0.geometry} material={materials.Plants} position={[-467.546, 16.021, -2159.717]} rotation={[-Math.PI / 2, 0, 0.097]} scale={100} />
        <mesh geometry={nodes.Pots_Large050_Plants_0.geometry} material={materials.Plants} position={[-482.244, 16.021, -2463.475]} rotation={[-Math.PI / 2, 0, 0.097]} scale={100} />
        <mesh geometry={nodes.Pots_Large054_Plants_0.geometry} material={materials.Plants} position={[-335.471, 14.014, -927.582]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large055_Plants_0.geometry} material={materials.Plants} position={[-335.272, 14.014, -1228.119]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large056_Plants_0.geometry} material={materials.Plants} position={[-337.54, 14.014, -1402.771]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large058_Plants_0.geometry} material={materials.Plants} position={[374.354, 14.014, -1408.176]} rotation={[-Math.PI / 2, 0, 1.501]} scale={100} />
        <mesh geometry={nodes.Pots_Large059_Plants_0.geometry} material={materials.Plants} position={[374.553, 14.014, -1228.119]} rotation={[-Math.PI / 2, 0, 1.826]} scale={100} />
        <mesh geometry={nodes.Pots_Large060_Plants_0.geometry} material={materials.Plants} position={[374.354, 14.014, -1776.258]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large061_Plants_0.geometry} material={materials.Plants} position={[328.672, 14.014, -1596.201]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large062_Plants_0.geometry} material={materials.Plants} position={[374.354, 14.014, -2123.319]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large063_Plants_0.geometry} material={materials.Plants} position={[374.354, 14.014, -2491.401]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large064_Plants_0.geometry} material={materials.Plants} position={[374.553, 14.014, -2311.343]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pots_Large066_Plants_0.geometry} material={materials.Plants} position={[-230.601, 125.64, -1217.541]} rotation={[-Math.PI / 2, 0, -0.752]} scale={100} />
        <mesh geometry={nodes.Pots_Large067_Plants_0.geometry} material={materials.Plants} position={[-240.342, 125.64, -2748.345]} rotation={[-Math.PI / 2, 0, 1.266]} scale={100} />
        <mesh geometry={nodes.Pots_Large071_Plants_0.geometry} material={materials.Plants} position={[349.21, 125.64, -2844.698]} rotation={[-Math.PI / 2, 0, 1.266]} scale={100} />
        <mesh geometry={nodes.Pots_Large079_Plants_0.geometry} material={materials.Plants} position={[-223.835, 14.014, -1811.253]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Bush_Bush_0.geometry} material={materials.Bush} position={[-1969.767, -33.125, 330.176]} rotation={[-Math.PI / 2, 0, 0]} scale={164.124} />
        <mesh geometry={nodes.Bush001_Bush_0.geometry} material={materials.Bush} position={[-1964.123, -33.125, -157.547]} rotation={[-Math.PI / 2, 0, 0.719]} scale={138.875} />
        <mesh geometry={nodes.Bush002_Bush_0.geometry} material={materials.Bush} position={[-1484.38, -33.125, -530.054]} rotation={[-Math.PI / 2, 0, 0.719]} scale={105.496} />
        <mesh geometry={nodes.Bush003_Bush_0.geometry} material={materials.Bush} position={[-2093.936, -33.125, -908.621]} rotation={[-Math.PI / 2, 0, 0.719]} scale={168.794} />
        <mesh geometry={nodes.Bush004_Bush_0.geometry} material={materials.Bush} position={[-1465.567, -33.125, -1117.974]} rotation={[-Math.PI / 2, 0, 1.534]} scale={105.496} />
        <mesh geometry={nodes.Bush005_Bush_0.geometry} material={materials.Bush} position={[-1872.407, -33.125, -1538.924]} rotation={[-Math.PI / 2, 0, 2.379]} scale={92.837} />
        <mesh geometry={nodes.Bush006_Bush_0.geometry} material={materials.Bush} position={[-1603.846, -33.125, -1868.63]} rotation={[-Math.PI / 2, 0, 1.534]} scale={73.847} />
        <mesh geometry={nodes.Bush007_Bush_0.geometry} material={materials.Bush} position={[-1917.089, -33.125, -2500.761]} rotation={[-Math.PI / 2, 0, 2.582]} scale={73.847} />
        <mesh geometry={nodes.Bush008_Bush_0.geometry} material={materials.Bush} position={[-1951.706, -33.125, -3371.225]} rotation={[-Math.PI / 2, 0, -1.55]} scale={118.156} />
        <mesh geometry={nodes.Bush009_Bush_0.geometry} material={materials.Bush} position={[-1543.228, -33.125, -2813.667]} rotation={[-Math.PI / 2, 0, -2.046]} scale={103.386} />
        <mesh geometry={nodes.Bush010_Bush_0.geometry} material={materials.Bush} position={[-1411.234, -33.125, -3188.359]} rotation={[-Math.PI / 2, 0, -0.764]} scale={94.524} />
        <mesh geometry={nodes.Bush011_Bush_0.geometry} material={materials.Bush} position={[-1370.597, -33.125, -3667.876]} rotation={[-Math.PI / 2, 0, -0.328]} scale={160.692} />
        <mesh geometry={nodes.Bush012_Bush_0.geometry} material={materials.Bush} position={[-1907.005, -33.125, -2172.433]} rotation={[-Math.PI / 2, 0, -1.55]} scale={176.761} />
        <mesh geometry={nodes.Bush013_Bush_0.geometry} material={materials.Bush} position={[-1279.088, -33.125, -2521.08]} rotation={[-Math.PI / 2, 0, -1.436]} scale={99.932} />
        <mesh geometry={nodes.Bush014_Bush_0.geometry} material={materials.Bush} position={[-606.62, -33.125, -3741.022]} rotation={[-Math.PI / 2, 0, -0.59]} scale={160.692} />
        <mesh geometry={nodes.Bush015_Bush_0.geometry} material={materials.Bush} position={[1795.028, -33.125, -3619.111]} rotation={[-Math.PI / 2, 0, 1.243]} scale={137.805} />
        <mesh geometry={nodes.Bush016_Bush_0.geometry} material={materials.Bush} position={[1635.181, -33.125, 128.873]} rotation={[-Math.PI / 2, 0, -0.175]} scale={89.015} />
        <mesh geometry={nodes.Bush017_Bush_0.geometry} material={materials.Bush} position={[1725.431, -33.125, -350.461]} rotation={[-Math.PI / 2, 0, 0.545]} scale={138.875} />
        <mesh geometry={nodes.Bush018_Bush_0.geometry} material={materials.Bush} position={[2262.571, -33.125, -634.001]} rotation={[-Math.PI / 2, 0, 0.545]} scale={105.496} />
        <mesh geometry={nodes.Bush019_Bush_0.geometry} material={materials.Bush} position={[1728.013, -33.125, -1112.666]} rotation={[-Math.PI / 2, 0, 0.545]} scale={135.035} />
        <mesh geometry={nodes.Bush020_Bush_0.geometry} material={materials.Bush} position={[1764.943, -33.125, -1644.162]} rotation={[-Math.PI / 2, 0, 0.236]} scale={131.3} />
        <mesh geometry={nodes.Bush021_Bush_0.geometry} material={materials.Bush} position={[1656.611, -33.125, -2119.736]} rotation={[-Math.PI / 2, 0, -2.449]} scale={138.875} />
        <mesh geometry={nodes.Bush022_Bush_0.geometry} material={materials.Bush} position={[2036.176, -33.125, -2593.914]} rotation={[-Math.PI / 2, 0, 0.955]} scale={105.496} />
        <mesh geometry={nodes.Bush023_Bush_0.geometry} material={materials.Bush} position={[1355.105, -33.125, -2819.776]} rotation={[-Math.PI / 2, 0, 0.955]} scale={119.438} />
        <mesh geometry={nodes.Bush024_Bush_0.geometry} material={materials.Bush} position={[1911.042, -33.125, -2929.835]} rotation={[-Math.PI / 2, 0, 2.264]} scale={119.438} />
        <mesh geometry={nodes.Bush025_Bush_0.geometry} material={materials.Bush} position={[1250.69, -33.125, -3556.323]} rotation={[-Math.PI / 2, 0, 2.264]} scale={119.438} />
        <mesh geometry={nodes.Bush026_Bush_0.geometry} material={materials.Bush} position={[1030.573, -33.125, -3423.688]} rotation={[-Math.PI / 2, 0, -3.123]} scale={95.663} />
        <mesh geometry={nodes.Bush027_Bush_0.geometry} material={materials.Bush} position={[889.472, -33.125, -3722.822]} rotation={[-Math.PI / 2, 0, 1.716]} scale={74.104} />
        <mesh geometry={nodes.Bush028_Bush_0.geometry} material={materials.Bush} position={[-1179.783, -33.125, 364.311]} rotation={[-Math.PI / 2, 0, -0.353]} scale={96.22} />
        <mesh geometry={nodes.Bush029_Bush_0.geometry} material={materials.Bush} position={[-1272.435, -33.125, -79.446]} rotation={[-Math.PI / 2, 0, -0.353]} scale={78.957} />
        <mesh geometry={nodes.Bush030_Bush_0.geometry} material={materials.Bush} position={[-866.079, -33.125, 232.647]} rotation={[-Math.PI / 2, 0, -0.353]} scale={49.18} />
        <mesh geometry={nodes.Bush031_Bush_0.geometry} material={materials.Bush} position={[2024.888, -33.125, 128.873]} rotation={[-Math.PI / 2, 0, 0.646]} scale={89.015} />
        <mesh geometry={nodes.Bush032_Bush_0.geometry} material={materials.Bush} position={[1635.181, -33.125, 390.848]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={88.367} />
        <mesh geometry={nodes.Bush033_Bush_0.geometry} material={materials.Bush} position={[1242.2, -33.125, 402.606]} rotation={[-Math.PI / 2, 0, -1.178]} scale={69.987} />
        <mesh geometry={nodes.Bush034_Bush_0.geometry} material={materials.Bush} position={[1280.077, -33.125, 61.612]} rotation={[-Math.PI / 2, 0, -1.927]} scale={57.892} />
        <mesh geometry={nodes.Bush035_Bush_0.geometry} material={materials.Bush} position={[1211.949, -33.125, -1497.297]} rotation={[-Math.PI / 2, 0, 1.688]} scale={86.217} />
        <mesh geometry={nodes.Bush036_Bush_0.geometry} material={materials.Bush} position={[1354.179, -33.125, -677.784]} rotation={[-Math.PI / 2, 0, -1.803]} scale={65.262} />
        <mesh geometry={nodes.Bush037_Bush_0.geometry} material={materials.Bush} position={[-1363.161, -33.125, -1654.383]} rotation={[-Math.PI / 2, 0, 1.534]} scale={69.432} />
        <mesh geometry={nodes.Bush038_Bush_0.geometry} material={materials.Bush} position={[-1153.474, -33.125, -1985.981]} rotation={[-Math.PI / 2, 0, -3.119]} scale={69.432} />
        <mesh geometry={nodes.Table_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -170]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table001_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -338.672]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table002_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -524.245]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table003_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -1163.108]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table004_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -1329.718]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table005_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -1504.079]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table006_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -1683.852]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table007_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -2057.147]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table008_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -2231.508]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table009_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -2411.281]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table010_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -2820.642]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table011_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[410, 0, -3000.416]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table012_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-721.205, 0, -1329.718]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table013_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-721.205, 0, -1166.854]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table014_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-721.205, 0, -854.399]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table015_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-721.205, 0, -1929.339]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table016_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-721.205, 0, -2715.121]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Table017_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-376.423, 0, -3032.511]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Table018_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-156.79, 0, -1147.324]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Table019_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[-207.688, 0, -2697.593]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Table020_WhiteMetal_0.geometry} material={materials.WhiteMetal} position={[381.864, 0, -2793.946]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/virtualGarden.gltf')
