/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cactus.gltf 
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cactus-f951db3894cf49448fd6359470a53580
Title: Cactus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cactus.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cactus_Material_#2143937762_0'].geometry} material={materials.Material_2143937762} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Igolki_Material_#2143937762_0'].geometry} material={materials.Material_2143937762} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cactus.gltf')
