/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 salviaRosmarinus.gltf 
Author: 🌴𝓜𝓪𝓻𝓽𝓪𝓻𝓴🌴 (https://sketchfab.com/adyatttt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/salvia-rosmarinus-c969c2a3fd29440a9e7b2ac87bf97cbb
Title: Salvia rosmarinus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/salviaRosmarinus.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.044, 0]} scale={0.248}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.material_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/salviaRosmarinus.gltf')
