/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Kyyy_24 (https://sketchfab.com/luckyardrianto27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/houseplant-2a6d61835f2b42e087cda41c007708d4
Title: HousePlant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0, 10.524]}>
          <mesh geometry={nodes.Aloevera_Aloe_vera_0.geometry} material={materials.Aloe_vera} />
          <mesh geometry={nodes.Aloevera_Aloe_vera_0_1.geometry} material={materials.Aloe_vera} />
          <mesh geometry={nodes.Aloevera_Aloe_vera_0_2.geometry} material={materials.Aloe_vera} />
        </group>
        <mesh geometry={nodes.Cube_Envi_0.geometry} material={materials.Envi} position={[0, 100.025, 0]} />
        <mesh geometry={nodes.Cube001_Envi_0.geometry} material={materials.Envi} position={[0, 100.025, 0]} />
        <mesh geometry={nodes.Wood_Envi_0.geometry} material={materials.Envi} position={[0, -99.975, 0]} />
        <mesh geometry={nodes.Pot_Envi_0.geometry} material={materials.Envi} position={[0, 0, 10.524]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
